/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ohjha;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/** GUI:n määrittely (Netbeans Swing), ja GUI:n buttonien määrittely. Buttonit johtavat Toimintoihin.
 *
 * @author Smoosh
 */
public class GUI extends javax.swing.JFrame {
    Toiminto toiminto = new Toiminto();
    FileHandling filehandling = new FileHandling();

    String output = "";
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        inputLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputField = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        countAAButton = new javax.swing.JButton();
        ProteinMassButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cnButton = new javax.swing.JButton();
        rcButton = new javax.swing.JButton();
        codonButton = new javax.swing.JButton();
        DProt = new javax.swing.JButton();
        dRNA = new javax.swing.JButton();
        reButton = new javax.swing.JButton();
        useAsInputButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        findField = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        inputField = new javax.swing.JTextField();
        compareField = new javax.swing.JTextField();
        compareButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fancy Program");
        setBackground(new java.awt.Color(255, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N

        inputLabel.setText("Input string or search for file, and choose command from the left.");

        outputLabel.setText("Output:");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        openButton.setText("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        outputField.setColumns(20);
        outputField.setRows(5);
        jScrollPane3.setViewportView(outputField);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proteins", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 10))); // NOI18N

        countAAButton.setText("Count Amino Acids");
        countAAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countAAButtonActionPerformed(evt);
            }
        });

        ProteinMassButton.setText("Protein Mass");
        ProteinMassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProteinMassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(countAAButton, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(ProteinMassButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(countAAButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProteinMassButton)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "DNA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 10), java.awt.Color.black)); // NOI18N

        cnButton.setText("Count Nucleotides");
        cnButton.setToolTipText("Counts all nucleotides, total, and GC%.");
        cnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnButtonActionPerformed(evt);
            }
        });

        rcButton.setText("Reverse Compliment");
        rcButton.setToolTipText("Makes a complimentary sequence and reverses it.");
        rcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcButtonActionPerformed(evt);
            }
        });

        codonButton.setText("Make Codons");
        codonButton.setToolTipText("Makes nucleotide triplets (codons).");
        codonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codonButtonActionPerformed(evt);
            }
        });

        DProt.setText("DNA -> Protein");
        DProt.setToolTipText("Converts DNA sequence to Protein sequence. If sequence contains several proteins, prints them on different lines.");
        DProt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DProtActionPerformed(evt);
            }
        });

        dRNA.setText("DNA -> RNA");
        dRNA.setToolTipText("Converts the DNA sequence to RNA sequence.");
        dRNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dRNAActionPerformed(evt);
            }
        });

        reButton.setText("Find RESite");
        reButton.setToolTipText("Finds Restriction Enzyme cutting sites in the DNA-sequence. Currently  known sites: NdeI, ");
        reButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dRNA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DProt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rcButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cnButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rcButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codonButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DProt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dRNA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        useAsInputButton.setText("Use As Input");
        useAsInputButton.setToolTipText("Uses the output field as input for further editing.");
        useAsInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useAsInputButtonActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N

        findButton.setText("Find");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        compareButton.setText("Compare");
        compareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Smoosh\\OhjHa\\OhjHa\\dna.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Smoosh\\OhjHa\\OhjHa\\dna.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputLabel)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(clearButton)
                                            .addGap(86, 86, 86)
                                            .addComponent(useAsInputButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(saveButton))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(findField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(findButton)
                                        .addGap(15, 15, 15)
                                        .addComponent(compareField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(compareButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(openButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitButton)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton)
                            .addComponent(clearButton)
                            .addComponent(exitButton)
                            .addComponent(useAsInputButton))
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(11, 11, 11)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(openButton)
                                                    .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(findField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(findButton)
                                                    .addComponent(compareField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(compareButton))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel2)))))
                        .addContainerGap(39, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** Kutsuu Protein Conversion metodia Toiminnosta.
     * @param this.inputField.getText() inputkentän tiedot
     * @param output Metodin output. 
     */
    private void DProtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DProtActionPerformed
        if (this.inputField.getText().length() > 0) {       
            output = toiminto.ProteinConversion(this.inputField.getText());
            outputField.setText(output);
        }
    }//GEN-LAST:event_DProtActionPerformed
    
    /** Kutsuu Find RESite metodia Toiminnosta.
     * @param this.inputField.getText() inputkentän tiedot
     * @param output Metodin output. 
     */
    private void reButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reButtonActionPerformed
        if (this.inputField.getText().length() > 0) {        
            output = toiminto.FindRESite(this.inputField.getText());
            outputField.setText(output);
        }
    }//GEN-LAST:event_reButtonActionPerformed
    
    /** Kutsuu Count Nucleotide metodia Toiminnosta.
     * @param this.inputField.getText() inputkentän tiedot
     * @param output Metodin output. 
     */
    private void cnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnButtonActionPerformed
        if (this.inputField.getText().length() > 0) {
            output = toiminto.CountNucleotides(this.inputField.getText());
            outputField.setText(output);
        }
    }//GEN-LAST:event_cnButtonActionPerformed
    
    /** Sulkee ohjelman.
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

     /** Clearaa molemmat kentät.
     */
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        inputField.setText("");
        outputField.setText("");
        compareField.setText("");
        findField.setText("");
        nameLabel.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed
    
     /** Kutsuu Reverse Compliment metodia Toiminnosta.
     * @param this.inputField.getText() inputkentän tiedot
     * @param output Metodin output. 
     */
    private void rcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcButtonActionPerformed
        if (this.inputField.getText().length() > 0) {
            output = toiminto.ReverseCompliment(this.inputField.getText());
            outputField.setText(output);
        }
    }//GEN-LAST:event_rcButtonActionPerformed
     /** Kutsuu Make Codons metodia Toiminnosta.
     * @param this.inputField.getText() inputkentän tiedot
     * @param output Metodin output. 
     */
    private void codonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codonButtonActionPerformed
        if (this.inputField.getText().length() > 0) {
            output = toiminto.MakeCodons(this.inputField.getText());
            outputField.setText(output);
        }
    }//GEN-LAST:event_codonButtonActionPerformed
    /** Kutsuu MakeRNA metodia Toiminnosta.
     * @param this.inputField.getText() inputkentän tiedot
     * @param output Metodin output. 
     */
    private void dRNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dRNAActionPerformed
        if (this.inputField.getText().length() > 0) {
            output = toiminto.MakeRNA(this.inputField.getText());
            outputField.setText(output);
        }
    }//GEN-LAST:event_dRNAActionPerformed
     /** Avaa tiedostonhaku-ikkunan ja hakee tiedoston inputFieldiin.
     */
    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(null);
        if (result == JFileChooser.CANCEL_OPTION) {
            return;
        }        
        try {
        File tiedosto = chooser.getSelectedFile();
        String filename = tiedosto.getAbsolutePath();
        String[] input = filehandling.Clean(filename);
        inputField.setText(input[0]);
        if (input[1] != "") {
            nameLabel.setText(input[1]);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "File not found.", "File Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_openButtonActionPerformed
     /** Tallentaa outputFieldissä olevan tiedon tiedostoon.
     */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        JFileChooser saver = new JFileChooser();
        int result = saver.showSaveDialog(this);
        if (result == JFileChooser.CANCEL_OPTION) {
            return;
        }
        File outputFile = saver.getSelectedFile();
        PrintWriter outputStream;

        try {
           outputStream = new PrintWriter(new BufferedWriter(
                          new FileWriter(outputFile)));
           outputStream.print(this.outputField.getText());
           outputStream.close();
        } catch(Exception e) {
           JOptionPane.showMessageDialog(this, "Error in saving to file.", "File Error", JOptionPane.ERROR_MESSAGE);
   }
    }//GEN-LAST:event_saveButtonActionPerformed
    /**
     * Siirtää output-fieldin tiedot input-fieldiin.
     * @param evt 
     */
    private void useAsInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useAsInputButtonActionPerformed
        if (this.inputField.getText().length() > 0) {
            output = outputField.getText();
            inputField.setText(output);
        }
    }//GEN-LAST:event_useAsInputButtonActionPerformed
    /**
     * Laskee aminohapot inpufieldistä, näyttää tuloksen outputfieldissä.
     * @param evt 
     */
    private void countAAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countAAButtonActionPerformed
       
        if (this.inputField.getText().length() > 0) {
            try {
                output = toiminto.CountProteins(this.inputField.getText());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            outputField.setText(output);
       }
    }//GEN-LAST:event_countAAButtonActionPerformed
    
    /**
     * Laskee proteiinimassan.
     * @param evt 
     */
    private void ProteinMassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProteinMassButtonActionPerformed
        if (this.inputField.getText().length() > 0) {
            try {
                output = toiminto.ProteinMass(this.inputField.getText());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            outputField.setText(output);
        }
    }//GEN-LAST:event_ProteinMassButtonActionPerformed
    /**
     * Etsii find fieldissä olevan stringin inputfieldistä.
     * @param evt 
     */
    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        
        if (this.findField.getText().length() > 0) {
            if (this.findField.getText().equals("darwin")) {
                Darwin darwin = new Darwin();
                darwin.setVisible(true);
            } else {
                output = toiminto.Find(this.inputField.getText(), this.findField.getText());
                outputField.setText(output);
            }
        }
    }//GEN-LAST:event_findButtonActionPerformed
/**
 * Vertaa inputfieldiä ja compareFieldiä keskenään.
 * @param evt 
 */
    private void compareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareButtonActionPerformed
        if (this.compareField.getText().length() > 0) {
            output = toiminto.Compare(this.inputField.getText(), this.compareField.getText());
            outputField.setText(output);
        }
        
    }//GEN-LAST:event_compareButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DProt;
    private javax.swing.JButton ProteinMassButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton cnButton;
    private javax.swing.JButton codonButton;
    private javax.swing.JButton compareButton;
    private javax.swing.JTextField compareField;
    private javax.swing.JButton countAAButton;
    private javax.swing.JButton dRNA;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton findButton;
    private javax.swing.JTextField findField;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton openButton;
    private javax.swing.JTextArea outputField;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JButton rcButton;
    private javax.swing.JButton reButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton useAsInputButton;
    // End of variables declaration//GEN-END:variables
}
